import type { AchievementDef } from '../types.js';

export const BUILTIN_ACHIEVEMENTS: AchievementDef[] = [
  // ─── Shipping ───────────────────────────────────────────────
  {
    id: 'first_blood',
    name: 'First Blood',
    description: 'Land your first commit',
    icon: '🩸',
    category: 'shipping',
    rarity: 'common',
    xpReward: 25,
    condition: { type: 'event_count', eventType: 'git.commit', count: 1 },
  },
  {
    id: 'shipper',
    name: 'Shipper',
    description: 'Get your first PR merged',
    icon: '📦',
    category: 'shipping',
    rarity: 'common',
    xpReward: 50,
    condition: { type: 'event_count', eventType: 'git.pr_merged', count: 1 },
  },
  {
    id: 'merge_machine',
    name: 'Merge Machine',
    description: 'Get 10 PRs merged',
    icon: '🔀',
    category: 'shipping',
    rarity: 'uncommon',
    xpReward: 100,
    condition: { type: 'event_count', eventType: 'git.pr_merged', count: 10 },
  },
  {
    id: 'release_captain',
    name: 'Release Captain',
    description: 'Successfully deploy 5 times',
    icon: '🚀',
    category: 'shipping',
    rarity: 'uncommon',
    xpReward: 150,
    condition: { type: 'event_count', eventType: 'deploy.success', count: 5 },
  },
  {
    id: 'centurion',
    name: 'Centurion',
    description: '100 commits strong',
    icon: '💯',
    category: 'shipping',
    rarity: 'rare',
    xpReward: 250,
    condition: { type: 'event_count', eventType: 'git.commit', count: 100 },
  },

  // ─── Quality ────────────────────────────────────────────────
  {
    id: 'test_pilot',
    name: 'Test Pilot',
    description: 'Run your first test suite',
    icon: '🧪',
    category: 'quality',
    rarity: 'common',
    xpReward: 25,
    condition: { type: 'event_count', eventType: 'test.suite_pass', count: 1 },
  },
  {
    id: 'green_wall',
    name: 'Green Wall',
    description: '50 passing test suites',
    icon: '🟢',
    category: 'quality',
    rarity: 'rare',
    xpReward: 200,
    condition: { type: 'event_count', eventType: 'test.suite_pass', count: 50 },
  },

  // ─── Consistency ────────────────────────────────────────────
  {
    id: 'on_a_roll_3',
    name: 'On a Roll',
    description: '3-day activity streak',
    icon: '🔥',
    category: 'consistency',
    rarity: 'common',
    xpReward: 50,
    condition: { type: 'streak', eventType: 'daily_activity' as any, count: 3 },
  },
  {
    id: 'on_a_roll_7',
    name: 'Week Warrior',
    description: '7-day activity streak',
    icon: '⚡',
    category: 'consistency',
    rarity: 'uncommon',
    xpReward: 100,
    condition: { type: 'streak', eventType: 'daily_activity' as any, count: 7 },
  },
  {
    id: 'on_a_roll_30',
    name: 'Monthly Machine',
    description: '30-day activity streak',
    icon: '⭐',
    category: 'consistency',
    rarity: 'epic',
    xpReward: 500,
    condition: { type: 'streak', eventType: 'daily_activity' as any, count: 30 },
  },
  {
    id: 'on_a_roll_100',
    name: 'Unstoppable',
    description: '100-day activity streak',
    icon: '👑',
    category: 'consistency',
    rarity: 'legendary',
    xpReward: 1000,
    condition: { type: 'streak', eventType: 'daily_activity' as any, count: 100 },
  },

  // ─── Milestone ──────────────────────────────────────────────
  {
    id: 'xp_1k',
    name: 'First Thousand',
    description: 'Earn 1,000 XP',
    icon: '🎯',
    category: 'milestone',
    rarity: 'common',
    xpReward: 50,
    condition: { type: 'xp_threshold', threshold: 1000 },
  },
  {
    id: 'level_5',
    name: 'Rising Star',
    description: 'Reach level 5',
    icon: '🌟',
    category: 'milestone',
    rarity: 'common',
    xpReward: 100,
    condition: { type: 'level_reached', level: 5 },
  },
  {
    id: 'level_10',
    name: 'Double Digits',
    description: 'Reach level 10',
    icon: '🏆',
    category: 'milestone',
    rarity: 'uncommon',
    xpReward: 250,
    condition: { type: 'level_reached', level: 10 },
  },
  {
    id: 'xp_10k',
    name: 'XP Hoarder',
    description: 'Earn 10,000 XP',
    icon: '💎',
    category: 'milestone',
    rarity: 'rare',
    xpReward: 250,
    condition: { type: 'xp_threshold', threshold: 10000 },
  },
  {
    id: 'level_20',
    name: 'Veteran',
    description: 'Reach level 20',
    icon: '🛡️',
    category: 'milestone',
    rarity: 'rare',
    xpReward: 500,
    condition: { type: 'level_reached', level: 20 },
  },
];
